---
title: "wk4hw"
author: "Stefan Krysa"
date: "2024-10-25"
output:
  html_document: default
  pdf_document: default
---

Calculating the change in gender inequality per country from 2010 to 2019, according to the UN gender inequality index:

```{r Data Processing, results=FALSE, message=FALSE, warning=FALSE}
##packages
library(countrycode)
library(here)
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)

##read data
gi_data <- read_csv(here('Data', 'GII.csv'))
countries <- st_read(here('Data','World_Countries_(Generalized)_9029012925078512962.geojson'))

##diff inequality 2010 to 2019
names(gi_data)
gi_data <- gi_data %>%
  mutate(gidiff = gii_2019 - gii_2010)
head(gi_data$gidiff)

##join data based on iso3code
countries$iso3 <- countrycode(countries$COUNTRY, 
                                      origin = "country.name", 
                                      destination = "iso3c")
gimap <- countries %>%
  merge(.,
        gi_data,
        by.x="iso3",
        by.y="iso3",
        no.dups=TRUE) 
```
Mapping the results: 

```{r Mapping Results, message=FALSE}
##create map
tmap_mode("plot")
tm_shape(gimap) +
  tm_polygons(
    col = "gidiff",         
    palette = "-RdBu",         
    title = "Change in GII"    
  ) +
  tm_layout(
    main.title = "Gender Inequality Index from 2010-2019",
    main.title.position = "center",
    main.title.size = 1.5,
    legend.position = c("left", "bottom"),
    legend.title.size = 0.9                
  )
```

